name: isatools
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - samtools
  - pip
  - pip:
      - pandas>=1.5.3,<2.0
      - numpy>=1.24.3,<1.26
      - scikit-learn>=1.2.2,<1.6
      - networkx>=2.8,<3.0
      - pysam>=0.19.1,<1.0
      - biopython>=1.79,<1.85
      - psutil>=6.0
      - pyarrow>=14.0.0
